import { MenuItem } from "./types";

const FOOD_IMAGES = {
  kebab: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&h=450&q=85",
  grill: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&h=450&q=85",
  wings: "https://images.unsplash.com/photo-1567626834653-3b64b5a4b0b0?auto=format&fit=crop&w=600&h=450&q=85",
  flatbread: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=600&h=450&q=85",
  chicken: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&h=450&q=85",
  kofte: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&h=450&q=85",
  fish: "https://images.unsplash.com/photo-1519708221-6c69289c3701?auto=format&fit=crop&w=600&h=450&q=85",
  falafel: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=600&h=450&q=85",
  hummus: "https://images.unsplash.com/photo-1572442383516-8c755542aea4?auto=format&fit=crop&w=600&h=450&q=85",
  fries: "https://images.unsplash.com/photo-1573080496219-a4188291a585?auto=format&fit=crop&w=600&h=450&q=85",
  wrap: "https://images.unsplash.com/photo-1626700051175-6818013e5786?auto=format&fit=crop&w=600&h=450&q=85",
  mandi: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&h=450&q=85",
  stew: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&h=450&q=85",
  gravy: "https://images.unsplash.com/photo-1604908176997-431637774376?auto=format&fit=crop&w=600&h=450&q=85",
  egg: "https://images.unsplash.com/photo-1482049860566-93c5f0a0f0a0?auto=format&fit=crop&w=600&h=450&q=85",
  bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&h=450&q=85",
  soup: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&h=450&q=85",
  kunafa: "https://images.unsplash.com/photo-1571877225908-a2318291a585?auto=format&fit=crop&w=600&h=450&q=85",
  chocolate: "https://images.unsplash.com/photo-1578985545068-69928b1d9587?auto=format&fit=crop&w=600&h=450&q=85",
  dessert: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&h=450&q=85",
  drink: "https://images.unsplash.com/photo-1622595465645-897c4130280d?auto=format&fit=crop&w=600&h=450&q=85",
  platter: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&h=450&q=85",
  hero: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&h=600&q=85",
};

const img = (key: keyof typeof FOOD_IMAGES) => FOOD_IMAGES[key];

export const CATEGORIES = [
  { id: "specials", name: "Turk Sarayi Specials", icon: "⭐" },
  { id: "starters", name: "Starters & Appetizers", icon: "🥙" },
  { id: "mandi", name: "Mandi", icon: "🍚" },
  { id: "mains", name: "Mains", icon: "🍲" },
  { id: "platters", name: "Special Platters", icon: "🍽️" },
  { id: "manakeesh", name: "Manakeesh & Breads", icon: "🫓" },
  { id: "soups", name: "Soups", icon: "🥣" },
  { id: "grilled", name: "Grilled Chicken", icon: "🍗" },
  { id: "kunafa", name: "Kunafa", icon: "🍰" },
  { id: "chocolate-kunafa", name: "Chocolate Kunafa", icon: "🍫" },
  { id: "special-kunafa", name: "Special Kunafa", icon: "✨" },
  { id: "desserts", name: "Desserts & More", icon: "🧁" },
  { id: "beverages", name: "Beverages", icon: "🥤" },
  { id: "extras", name: "Extras", icon: "➕" },
];

export const MENU_ITEMS: MenuItem[] = [
  // SPECIALS
  {
    id: "adana-mutton",
    name: "Adana Kebab (Mutton)",
    description: "2 skewers of rich, savory Adana kebab — a true taste of Turkish culinary tradition.",
    category: "specials",
    priceType: "single",
    price: 450,
    image: img("kebab"),
    dietary: ["non-veg", "spicy"],
  },
  {
    id: "adana-chicken",
    name: "Adana Kebab (Chicken)",
    description: "2 skewers of spicy minced chicken kebab grilled with special Turkish sauce.",
    category: "specials",
    priceType: "single",
    price: 320,
    image: img("kebab"),
    dietary: ["non-veg", "spicy"],
  },
  {
    id: "turkish-wings",
    name: "Turkish Wings (Kanat)",
    description: "Succulent chicken wings marinated in yogurt, garlic, paprika, cumin and herbs, grilled to smoky perfection.",
    category: "specials",
    priceType: "single",
    price: 350,
    image: img("wings"),
    dietary: ["non-veg", "spicy"],
  },
  {
    id: "lahmacun",
    name: "Lahmacun",
    description: "Turkish flatbread topped with minced meat, herbs and spices, served with a skewer of spicy minced lamb kebab.",
    category: "specials",
    priceType: "single",
    price: 160,
    image: img("flatbread"),
    dietary: ["non-veg"],
  },
  {
    id: "shish-taouk",
    name: "Shish Taouk",
    description: "Tender chicken cubes marinated in yogurt, lemon, garlic and Turkish spices, grilled on skewers.",
    category: "specials",
    priceType: "single",
    price: 320,
    image: img("grill"),
    dietary: ["non-veg"],
  },
  {
    id: "beyti-mutton",
    name: "Beyti Kebab (Mutton)",
    description: "Ground lamb wrapped in lavash bread, char-grilled and served with tomato sauce and creamy yogurt.",
    category: "specials",
    priceType: "single",
    price: 300,
    image: img("grill"),
    dietary: ["non-veg"],
  },
  {
    id: "beyti-chicken",
    name: "Beyti Kebab (Chicken)",
    description: "Grilled minced chicken wrapped in lavash bread, served with a special sauce.",
    category: "specials",
    priceType: "single",
    price: 200,
    image: img("grill"),
    dietary: ["non-veg"],
  },
  {
    id: "arabian-white-chicken",
    name: "Arabian White Chicken",
    description: "Tender chicken marinated in creamy yogurt and special spice blend, slow-cooked to perfection.",
    category: "specials",
    priceType: "single",
    price: 320,
    image: img("chicken"),
    dietary: ["non-veg"],
  },
  {
    id: "kessap-kofte",
    name: "Turkish Kessap Kofte",
    description: "Tender mutton patties marinated in creamy yogurt and special spices, slow-cooked to perfection.",
    category: "specials",
    priceType: "single",
    price: 450,
    image: img("kofte"),
    dietary: ["non-veg"],
  },

  // STARTERS
  {
    id: "grill-samak",
    name: "Grill Samak (Fish)",
    description: "Fresh fish grilled with Turkish spices and herbs.",
    category: "starters",
    priceType: "single",
    price: 300,
    image: img("fish"),
    dietary: ["non-veg"],
  },
  {
    id: "falafel",
    name: "Falafel (6 Pcs)",
    description: "Crispy falafel made from ground chickpeas, fresh herbs and aromatic spices.",
    category: "starters",
    priceType: "single",
    price: 180,
    image: img("falafel"),
    dietary: ["veg"],
  },
  {
    id: "hummus",
    name: "Hummus",
    description: "Classic creamy hummus served with warm lavash bread.",
    category: "starters",
    priceType: "single",
    price: 200,
    image: img("hummus"),
    dietary: ["veg"],
  },
  {
    id: "chicken-hummus",
    name: "Chicken Hummus",
    description: "Creamy hummus topped with seasoned chicken, served with 2 lavash bread.",
    category: "starters",
    priceType: "single",
    price: 249,
    image: img("hummus"),
    dietary: ["non-veg"],
  },
  {
    id: "classic-hummus",
    name: "Classic Hummus",
    description: "Traditional hummus served with 2 lavash bread.",
    category: "starters",
    priceType: "single",
    price: 199,
    image: img("hummus"),
    dietary: ["veg"],
  },
  {
    id: "french-fries",
    name: "French Fries",
    description: "Crispy golden fries — choose salted, peri peri, or loaded.",
    category: "starters",
    priceType: "portions",
    portions: [
      { label: "Salted", price: 140 },
      { label: "Peri Peri", price: 160 },
      { label: "Loaded", price: 250 },
    ],
    image: img("fries"),
    dietary: ["veg"],
  },
  {
    id: "turkish-wrap",
    name: "Special Turkish Wrap",
    description: "Grilled meat and fresh vegetables wrapped in lavash with Turkish sauce.",
    category: "starters",
    priceType: "single",
    price: 170,
    image: img("wrap"),
    dietary: ["non-veg"],
  },
  {
    id: "spicy-turkish-wrap",
    name: "Spicy Turkish Wrap",
    description: "Spicy grilled filling wrapped in lavash with garlic sauce.",
    category: "starters",
    priceType: "single",
    price: 180,
    image: img("wrap"),
    dietary: ["non-veg", "spicy"],
  },

  // MANDI
  {
    id: "mutton-mandi",
    name: "Mutton Mandi",
    description: "Traditional Yemeni-style mandi with tender mutton and fragrant rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 550 },
      { label: "3 Person", price: 700 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },
  {
    id: "mutton-juicy-mandi",
    name: "Mutton Juicy Mandi",
    description: "Extra juicy mutton mandi with rich, aromatic rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 600 },
      { label: "3 Person", price: 750 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },
  {
    id: "mutton-haneedh-mandi",
    name: "Mutton Haneedh Mandi",
    description: "Weekend special — slow-roasted mutton mandi with signature spices.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 600 },
      { label: "3 Person", price: 750 },
    ],
    image: img("mandi"),
    dietary: ["non-veg", "weekend-special"],
    note: "Available on weekends",
  },
  {
    id: "grill-chicken-mandi",
    name: "Grill Chicken Mandi",
    description: "Grilled chicken served over fragrant mandi rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 450 },
      { label: "3 Person", price: 680 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },
  {
    id: "chicken-fry-mandi",
    name: "Chicken Fry Mandi",
    description: "Crispy fried chicken with aromatic mandi rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 420 },
      { label: "3 Person", price: 650 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },
  {
    id: "chicken-juicy-mandi",
    name: "Chicken Juicy Mandi",
    description: "Juicy chicken mandi with perfectly seasoned rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 450 },
      { label: "3 Person", price: 680 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },
  {
    id: "fish-mandi",
    name: "Fish Mandi",
    description: "Fresh fish mandi with fragrant spiced rice.",
    category: "mandi",
    priceType: "portions",
    portions: [
      { label: "2 Person", price: 400 },
      { label: "3 Person", price: 650 },
    ],
    image: img("mandi"),
    dietary: ["non-veg"],
  },

  // MAINS
  {
    id: "aqdah-chicken",
    name: "Aqdah Chicken",
    description: "Small pieces of chicken cooked with vegetables in a hearty stew.",
    category: "mains",
    priceType: "single",
    price: 350,
    image: img("stew"),
    dietary: ["non-veg"],
  },
  {
    id: "turkish-chicken-gravy",
    name: "Turkish Chicken Gravy",
    description: "Tender chicken cooked in rich Turkish-style gravy.",
    category: "mains",
    priceType: "single",
    price: 300,
    image: img("gravy"),
    dietary: ["non-veg"],
  },
  {
    id: "yemeni-egg-lahsa",
    name: "Yemeni Egg Lahsa with Cheese",
    description: "Poached eggs in spiced tomato sauce, topped with melted Yemeni cheese.",
    category: "mains",
    priceType: "single",
    price: 180,
    image: img("egg"),
    dietary: ["veg"],
  },
  {
    id: "mutton-fahsa",
    name: "Mutton Fahsa",
    description: "Tender mutton slow-cooked in a rich Yemeni stew with spices and herbs.",
    category: "mains",
    priceType: "single",
    price: 400,
    image: img("stew"),
    dietary: ["non-veg", "spicy"],
  },
  {
    id: "cihan-kebab-chicken",
    name: "Cihan Kebab (Chicken)",
    description: "Tender kebabs filled with melted cheese, served on pita with tomato sauce and yogurt.",
    category: "mains",
    priceType: "single",
    price: 300,
    image: img("kebab"),
    dietary: ["non-veg"],
  },
  {
    id: "cihan-kebab-mutton",
    name: "Cihan Kebab (Mutton)",
    description: "Tender mutton kebabs filled with melted cheese, served on pita with tomato sauce and yogurt.",
    category: "mains",
    priceType: "single",
    price: 450,
    image: img("kebab"),
    dietary: ["non-veg"],
  },
  {
    id: "testi-kebab",
    name: "Testi Kebab",
    description: "Spicy roasted potatoes and mutton with Middle Eastern spices, cooked in a clay pot.",
    category: "mains",
    priceType: "single",
    price: 380,
    image: img("stew"),
    dietary: ["non-veg", "spicy"],
  },
  {
    id: "izmir-kofte-chicken",
    name: "Izmir Kofte (Chicken)",
    description: "Spiced chicken meatballs cooked in a rich tomato and pepper sauce.",
    category: "mains",
    priceType: "single",
    price: 350,
    image: img("kofte"),
    dietary: ["non-veg"],
  },
  {
    id: "izmir-kofte-mutton",
    name: "Izmir Kofte (Mutton)",
    description: "Spiced mutton meatballs cooked in a rich tomato and pepper sauce.",
    category: "mains",
    priceType: "single",
    price: 450,
    image: img("kofte"),
    dietary: ["non-veg"],
  },

  // PLATTERS
  {
    id: "turkish-chicken-platter",
    name: "Turkish Chicken Platter (2 persons)",
    description: "Chicken Adana, Turkish Wings, Beyti Kebab, Arabian White Chicken, Shish Tawook, Falafel with grilled veggies, fries and lavash.",
    category: "platters",
    priceType: "single",
    price: 799,
    image: img("platter"),
    dietary: ["non-veg"],
  },
  {
    id: "mixed-turkish-platter",
    name: "Mixed Turkish Platter",
    description: "Mutton & chicken Adana, Shish Tawook, Wings, Mutton Chops, Grilled Samak, Falafel, fries, garlic sauce, lavash and grilled veggies.",
    category: "platters",
    priceType: "single",
    price: 1499,
    image: img("platter"),
    dietary: ["non-veg"],
  },
  {
    id: "mutton-platter",
    name: "Mutton Platter",
    description: "Adana Kebab, Beyti Kebab, Mutton Chops, Halabi Kebab with lavash, fries and garlic sauce.",
    category: "platters",
    priceType: "single",
    price: 1899,
    image: img("platter"),
    dietary: ["non-veg"],
  },

  // MANAKEESH & BREADS
  {
    id: "mutton-lamhacun",
    name: "Mutton Lamhacun",
    description: "Thin, crispy flatbread topped with minced mutton and spiced sauce.",
    category: "manakeesh",
    priceType: "single",
    price: 250,
    image: img("flatbread"),
    dietary: ["non-veg"],
  },
  {
    id: "chicken-lamhacun",
    name: "Chicken Lamhacun",
    description: "Thin, crispy flatbread topped with minced chicken and spiced sauce.",
    category: "manakeesh",
    priceType: "single",
    price: 160,
    image: img("flatbread"),
    dietary: ["non-veg"],
  },
  {
    id: "cheese-pide",
    name: "Cheese Pide",
    description: "Boat-shaped flatbread filled with melted cheese and spiced sauce.",
    category: "manakeesh",
    priceType: "single",
    price: 180,
    image: img("falafel"),
    dietary: ["veg"],
  },
  {
    id: "chicken-cheese-pide",
    name: "Chicken Cheese Pide",
    description: "Boat-shaped flatbread filled with melted cheese, seasoned chicken and spiced sauce.",
    category: "manakeesh",
    priceType: "single",
    price: 220,
    image: img("falafel"),
    dietary: ["non-veg"],
  },
  {
    id: "lavash-bread",
    name: "Lavash Bread",
    description: "Traditional thin Turkish flatbread.",
    category: "manakeesh",
    priceType: "single",
    price: 20,
    image: img("bread"),
    dietary: ["veg"],
  },
  {
    id: "rumali-roti",
    name: "Rumali Roti",
    description: "Paper-thin handkerchief bread.",
    category: "manakeesh",
    priceType: "single",
    price: 25,
    image: img("bread"),
    dietary: ["veg"],
  },

  // SOUPS
  {
    id: "mutton-soup",
    name: "Mutton Soup",
    description: "Hearty savory broth made with tender mutton and rich spices.",
    category: "soups",
    priceType: "single",
    price: 120,
    image: img("soup"),
    dietary: ["non-veg"],
  },

  // GRILLED CHICKEN
  {
    id: "lebanese-grill-chicken",
    name: "Lebanese Grill Chicken",
    description: "Flavourful grilled chicken injected with Turkish masala, served with lavash bread and garlic sauce.",
    category: "grilled",
    priceType: "portions",
    portions: [
      { label: "Half", price: 250 },
      { label: "Full", price: 480 },
    ],
    image: img("chicken"),
    dietary: ["non-veg"],
  },
  {
    id: "faham-chicken",
    name: "Faham Chicken",
    description: "Smoky grilled chicken marinated in Arabian spices.",
    category: "grilled",
    priceType: "portions",
    portions: [
      { label: "Half", price: 270 },
      { label: "Full", price: 500 },
    ],
    image: img("chicken"),
    dietary: ["non-veg"],
  },

  // KUNAFA
  ...[
    ["cream-kunafa", "Cream Kunafa", [200, 250, 380]],
    ["cream-cheese-kunafa", "Cream Cheese Kunafa", [250, 330, 420]],
    ["nutella-kunafa", "Nutella Kunafa", [250, 330, 420]],
    ["nutella-cheese-kunafa", "Nutella Cheese Kunafa", [300, 350, 450]],
    ["cheese-kunafa", "Cheese Kunafa", [300, 380, 450]],
  ].map(([id, name, prices]) => ({
    id: id as string,
    name: name as string,
    description: "Traditional Turkish kunafa made with fine shredded pastry and sweet syrup.",
    category: "kunafa",
    priceType: "sizes" as const,
    sizes: [
      { label: "Small", price: (prices as number[])[0] },
      { label: "Medium", price: (prices as number[])[1] },
      { label: "Large", price: (prices as number[])[2] },
    ],
    image: img("kunafa"),
    dietary: ["veg" as const],
  })),

  // CHOCOLATE KUNAFA
  ...[
    ["white-chocolate-kunafa", "White Chocolate Kunafa", [250, 380, 420]],
    ["milk-chocolate-kunafa", "Milk Chocolate Kunafa", [250, 380, 420]],
    ["dark-chocolate-kunafa", "Dark Chocolate Kunafa", [250, 380, 420]],
    ["triple-chocolate-kunafa", "Triple Chocolate Kunafa", [270, 350, 470]],
  ].map(([id, name, prices]) => ({
    id: id as string,
    name: name as string,
    description: "Rich chocolate kunafa with layers of crispy pastry and decadent filling.",
    category: "chocolate-kunafa",
    priceType: "sizes" as const,
    sizes: [
      { label: "Small", price: (prices as number[])[0] },
      { label: "Medium", price: (prices as number[])[1] },
      { label: "Large", price: (prices as number[])[2] },
    ],
    image: img("chocolate"),
    dietary: ["veg" as const],
  })),

  // SPECIAL KUNAFA
  ...[
    ["almond-kunafa", "Almond Kunafa", [300, 380, 450]],
    ["cashew-kunafa", "Cashew Kunafa", [300, 380, 450]],
    ["pista-kunafa", "Pista Kunafa", [300, 400, 550]],
    ["dry-fruit-kunafa", "Dry Fruit Kunafa", [300, 350, 450]],
    ["strawberry-kunafa", "Strawberry Kunafa", [300, 380, 450]],
    ["blueberry-kunafa", "Blueberry Kunafa", [300, 380, 450]],
    ["lotus-kunafa", "Lotus Biscoff Kunafa", [300, 380, 450]],
  ].map(([id, name, prices]) => ({
    id: id as string,
    name: name as string,
    description: "Premium kunafa with specialty toppings and sweet syrup.",
    category: "special-kunafa",
    priceType: "sizes" as const,
    sizes: [
      { label: "Small", price: (prices as number[])[0] },
      { label: "Medium", price: (prices as number[])[1] },
      { label: "Large", price: (prices as number[])[2] },
    ],
    image: img("kunafa"),
    dietary: ["veg" as const],
  })),

  // DESSERTS & MORE
  {
    id: "umm-ali-regular",
    name: "Umm Ali Regular",
    description: "Classic Egyptian bread pudding with milk, nuts and raisins.",
    category: "desserts",
    priceType: "single",
    price: 150,
    image: img("dessert"),
    dietary: ["veg"],
  },
  {
    id: "umm-ali-nuts",
    name: "Umm Ali with Nuts",
    description: "Umm Ali topped with mixed nuts.",
    category: "desserts",
    priceType: "single",
    price: 200,
    image: img("dessert"),
    dietary: ["veg"],
  },
  {
    id: "umm-ali-nutella",
    name: "Umm Ali with Nutella",
    description: "Umm Ali with rich Nutella drizzle.",
    category: "desserts",
    priceType: "single",
    price: 200,
    image: img("dessert"),
    dietary: ["veg"],
  },
  {
    id: "umm-ali-lotus",
    name: "Umm Ali with Lotus",
    description: "Umm Ali with Lotus Biscoff topping.",
    category: "desserts",
    priceType: "single",
    price: 220,
    image: img("dessert"),
    dietary: ["veg"],
  },
  {
    id: "san-sebastian-cake",
    name: "San Sebastian Cheese Cake",
    description: "Burnt Basque-style cheesecake with a creamy center.",
    category: "desserts",
    priceType: "single",
    price: 180,
    image: img("chocolate"),
    dietary: ["veg"],
  },
  {
    id: "san-sebastian-nutella",
    name: "San Sebastian with Nutella",
    description: "San Sebastian cheesecake with Nutella topping.",
    category: "desserts",
    priceType: "single",
    price: 220,
    image: img("chocolate"),
    dietary: ["veg"],
  },
  ...[
    ["turkish-kashtuta", "Turkish Kashtuta", 200],
    ["nutella-kashtuta", "Nutella Kashtuta", 250],
    ["pista-kashtuta", "Pista Kashtuta", 280],
    ["lotus-kashtuta", "Lotus Biscoff Kashtuta", 280],
    ["triple-chocolate-kashtuta", "Triple Chocolate Kashtuta", 280],
    ["mango-kashtuta", "Mango Kashtuta (Seasonal)", 280],
  ].map(([id, name, price]) => ({
    id: id as string,
    name: name as string,
    description: "Soft milk cake soaked in cream — a Turkish dessert favorite.",
    category: "desserts",
    priceType: "single" as const,
    price: price as number,
    image: img("chocolate"),
    dietary: ["veg" as const],
  })),
  ...[
    ["nutella-koshari", "Nutella Koshari", [180, 320]],
    ["lotus-koshari", "Lotus Biscoff Koshari", [220, 350]],
    ["pista-koshari", "Pista Koshari", [220, 370]],
    ["triple-chocolate-koshari", "Triple Chocolate Koshari", [200, 350]],
    ["mango-koshari", "Mango Koshari", [200, 320]],
  ].map(([id, name, prices]) => ({
    id: id as string,
    name: name as string,
    description: "Introducing first time in India — sweet koshari dessert fusion.",
    category: "desserts",
    priceType: "portions" as const,
    portions: [
      { label: "Half", price: (prices as number[])[0] },
      { label: "Full", price: (prices as number[])[1] },
    ],
    image: img("chocolate"),
    dietary: ["veg" as const],
  })),

  // BEVERAGES
  {
    id: "ardeb-juice",
    name: "Ardeb Juice",
    description: "Refreshing traditional juice.",
    category: "beverages",
    priceType: "single",
    price: 40,
    image: img("drink"),
    dietary: ["veg"],
  },
  {
    id: "saudi-champagne",
    name: "Saudi Champagne",
    description: "Sparkling apple mocktail — a Middle Eastern favorite.",
    category: "beverages",
    priceType: "single",
    price: 80,
    image: img("drink"),
    dietary: ["veg"],
  },
  {
    id: "soft-drink",
    name: "Soft Drink",
    description: "Thumsup, Sprite or Campa.",
    category: "beverages",
    priceType: "single",
    price: 20,
    image: img("drink"),
    dietary: ["veg"],
  },
  {
    id: "water",
    name: "Water",
    description: "Bottled water — small or large.",
    category: "beverages",
    priceType: "portions",
    portions: [
      { label: "Small", price: 10 },
      { label: "Large", price: 20 },
    ],
    image: img("drink"),
    dietary: ["veg"],
  },

  // EXTRAS
  ...[
    ["extra-ice-cream", "Extra Ice Cream", 50],
    ["extra-nuts", "Extra Nuts", 50],
    ["extra-nutella", "Extra Nutella", 50],
    ["extra-lotus", "Extra Lotus Biscoff", 60],
    ["extra-pista", "Extra Pista", 60],
    ["extra-chocolate", "Extra Chocolate", 50],
    ["extra-syrup", "Extra Syrup", 20],
  ].map(([id, name, price]) => ({
    id: id as string,
    name: name as string,
    description: "Add-on for your dessert order.",
    category: "extras",
    priceType: "single" as const,
    price: price as number,
    image: img("chocolate"),
    dietary: ["veg" as const],
  })),
];

export function getMenuItem(id: string): MenuItem | undefined {
  return MENU_ITEMS.find((item) => item.id === id);
}

export function getItemsByCategory(categoryId: string): MenuItem[] {
  return MENU_ITEMS.filter((item) => item.category === categoryId);
}

export function formatPrice(amount: number): string {
  return `₹${amount.toLocaleString("en-IN")}`;
}

export function getDisplayPrice(item: MenuItem): string {
  if (item.priceType === "single" && item.price) {
    return formatPrice(item.price);
  }
  if (item.sizes) {
    const min = Math.min(...item.sizes.map((s) => s.price));
    const max = Math.max(...item.sizes.map((s) => s.price));
    return min === max ? formatPrice(min) : `${formatPrice(min)} – ${formatPrice(max)}`;
  }
  if (item.portions) {
    const min = Math.min(...item.portions.map((p) => p.price));
    const max = Math.max(...item.portions.map((p) => p.price));
    return min === max ? formatPrice(min) : `${formatPrice(min)} – ${formatPrice(max)}`;
  }
  return "";
}

export const DIETARY_LABELS: Record<string, { label: string; color: string }> = {
  veg: { label: "Veg", color: "#2e7d32" },
  "non-veg": { label: "Non-Veg", color: "#c62828" },
  spicy: { label: "Spicy", color: "#e65100" },
  "weekend-special": { label: "Weekend", color: "#6a1b9a" },
};
